# Generated by Django 4.2.7 on 2026-06-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('range_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lanereservation',
            name='number_of_people',
            field=models.IntegerField(default=1, verbose_name='预约人数'),
        ),
        migrations.AddField(
            model_name='riskwarning',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='处理时限'),
        ),
    ]
